### Numpy Assignment

1. Write a function so that the columns of the output matrix are powers of the input 
 vector. 
 
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1. 

In [1]:
import numpy as np 

In [33]:
def vender_like(a, Y):
    return np.column_stack([a**(Y-1-i) for i in range(Y)])
a  =np.array([1,2,4,5])
vender_like(a, Y=4)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 64,  16,   4,   1],
       [125,  25,   5,   1]], dtype=int32)

In [5]:
np.vander(a,Y)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 64,  16,   4,   1],
       [125,  25,   5,   1]])

#### So, in either way, we can obtain the desired result 

2. Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 

In [32]:
def moving_average(a, n=3):
    a_sum = np.cumsum(a, dtype=float)
    a_sum[n:] = a_sum[n:] - a_sum[:-n]
    return a_sum[n-1:]/3

b = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
a = np.array(b)
np.array(moving_average(a, n=3)).round(2)

array([  5.  ,   4.67,   5.67,   6.67,   9.67,  28.67,  49.33,  72.67,
        84.  ,  93.33, 116.33])